services:
  - type: web
    name: patient-data-viewer
    env: python
    buildCommand: pip install -r Frontend/requirements.txt
    startCommand: gunicorn Frontend.app:app
    envVars:
      - key: SUPABASE_URL
        value: https://wjqlervxbljhkscrteld.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqcWxlcnZ4YmxqaGtzY3J0ZWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MjgxODUsImV4cCI6MjA1OTQwNDE4NX0.UJiOIJPtD4sY6Tgscur8RouPi-0jPIIYJuC18uerqyQ

